### ISSUE TITLE
Won't show up in Must-Use plugins section

### ISSUE THREAD

**Issue by GitHubGreg** [danielbachhuber/mandrill-wp-mail#13]
Thank you for sharing this tool.

When I add it to the mu-plugins folder it doesn't show up in the WordPress Must-Use plugins section (but other custom mu plugins do). And when I try to put it inside the regular plugins folder I get the error:

Fatal error: Cannot redeclare wp_mail() (previously declared in /home/content/p3pnexwpnas08_data01/65/2546865/html/wp-includes/pluggable.php:224) in/home/content/p3pnexwpnas08_data01/65/2546865/html/wp-content/plugins/mandrill-wp-mail-master/mandrill-wp-mail.php on line 134

Do you have any thoughts on what could be causing this? It is for a client who is using GoDaddy Managed WordPress hosting, and that is the reason I need it (Hotmail simply refuses emails from the site due to an ongoing issue with GoDaddy and Hotmail).

**Comment by danielbachhuber** [comment]
> When I add it to the mu-plugins folder it doesn't show up in the WordPress Must-Use plugins section (but other custom mu plugins do).

How have you added it to `mu-plugins`? Are you sure it's being loaded?

**Comment by GitHubGreg** [comment]
Yes I did add it to the mu-plugins folder but it didn't show up in Wordpress's must use plugin's section (but others do). When I add it to the regular plugins folder (as a test) and activate it, I get the error mentioned in my original post.

**Comment by danielbachhuber** [comment]
Can you be more explicit about how you've added it to mu-plugins?

**Comment by GitHubGreg** [comment]
I downloaded the file from github and extracted it.
I placed the "mandrill-wp-mail-master" folder into the "mu-plugins" folder.

**Comment by danielbachhuber** [comment]
> I placed the "mandrill-wp-mail-master" folder into the "mu-plugins" folder.

You're not actually loading the plugin then. WordPress doesn't recursively scan the mu-plugins directory. You'll need to actually load the plugin.

I've updated the "How To Use" description in the readme with an example: https://github.com/danielbachhuber/mandrill-wp-mail/blob/master/README.md#how-to-use

**Comment by GitHubGreg** [comment]
That did the trick, thanks (I could have remembered that mu plugins need to be loaded, sorry about that).

The update you added is great, just note that the directory is mandrill-wp-mail-master (not mandrill-wp-mail).

Thanks again.
